services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  app:
    build: .
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - 127.0.0.1:8000:8000
    env_file: server/.env
